
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 23 00:22:45 CST 2020
//----------------------------------------------------

package analizadores.pnt;

/** CUP generated class containing symbol constants. */
public class SimbolosPnt {
  /* terminals */
  public static final int DIAGONAL = 17;
  public static final int NUMERO = 34;
  public static final int COMENTAR_LINEA = 11;
  public static final int LLAVES_C = 8;
  public static final int VARS = 12;
  public static final int LLAVES_A = 7;
  public static final int DIFERENTE = 42;
  public static final int DOS_PUNTOS = 4;
  public static final int CORCHETE_C = 3;
  public static final int INT = 24;
  public static final int CORCHETE_A = 2;
  public static final int ASTERISCO = 16;
  public static final int INSTRUCCIONES = 32;
  public static final int IDENTIFICADOR = 9;
  public static final int AND = 30;
  public static final int IGUAL = 13;
  public static final int PUNTO_PUNTO = 43;
  public static final int OR = 31;
  public static final int IF = 27;
  public static final int IGUAL_IGUAL = 41;
  public static final int PUNTO_COMA = 10;
  public static final int EOF = 0;
  public static final int BOOLEAN = 26;
  public static final int COMENTAR_C = 36;
  public static final int TRUE = 37;
  public static final int COMILLAS = 6;
  public static final int COMENTAR_A = 35;
  public static final int error = 1;
  public static final int PINTAR = 33;
  public static final int COMA = 5;
  public static final int MENOS = 15;
  public static final int PINTAR_MIN = 23;
  public static final int MAYOR_QUE = 19;
  public static final int ELSE = 28;
  public static final int PUNTO = 22;
  public static final int PARENTESIS_C = 21;
  public static final int WHILE = 29;
  public static final int PARENTESIS_A = 20;
  public static final int MAYOR_IGUAL = 39;
  public static final int STRING = 25;
  public static final int MENOR_QUE = 18;
  public static final int MENOR_IGUAL = 40;
  public static final int FALSE = 38;
  public static final int SALTO = 44;
  public static final int MAS = 14;
}

