
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 21 17:25:41 CST 2020
//----------------------------------------------------

package analizadores.clrs;

/** CUP generated class containing symbol constants. */
public class SimbolosClrs {
  /* terminals */
  public static final int GREEN = 22;
  public static final int LLAVES_C = 8;
  public static final int CODIGO_HEX = 14;
  public static final int LLAVES_A = 7;
  public static final int PNG = 17;
  public static final int BLUE = 21;
  public static final int RED = 20;
  public static final int COMILLAS = 6;
  public static final int CORCHE_C = 3;
  public static final int HEX = 19;
  public static final int DOS_PUNTOS = 4;
  public static final int TIPO = 16;
  public static final int CORCHE_A = 2;
  public static final int COLORES = 9;
  public static final int COMA = 5;
  public static final int CUADRO = 23;
  public static final int NOMBRE = 15;
  public static final int EOF = 0;
  public static final int FONDO = 13;
  public static final int GIF = 18;
  public static final int error = 1;
  public static final int NUMERO = 12;
  public static final int DIMENSION_Y = 25;
  public static final int DIMENSION_X = 24;
  public static final int IDENTIFICADOR = 11;
  public static final int TAMANIO = 10;
}

