/* The following code was generated by JFlex 1.4.3 on 22/05/20 03:03 PM */

package analizadores.tmp;
import java_cup.runtime.*;
import objetos.ErrorG;
import java.util.ArrayList;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 22/05/20 03:03 PM from the specification file
 * <tt>Lexer.jflex</tt>
 */
public class AnalizadorLexicoTmp implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  8, 39,  0,  0,  8,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     8,  0, 38, 41,  0,  0,  0,  0,  0,  0,  0,  0, 47,  0, 40,  0, 
     6,  6,  6,  6,  6,  6,  6,  6,  6,  7, 42,  0,  0,  0,  0,  0, 
     0,  5,  5,  5, 27, 11, 25,  1, 30, 10,  1,  1,  1, 12, 26, 14, 
    13,  1, 28, 15,  9,  1,  1,  1, 31,  1,  1, 43,  0, 44,  0,  1, 
     0, 32, 19, 33, 29, 21, 34, 35,  1, 23,  1,  1,  1, 18, 16, 17, 
    24,  1, 20, 36, 22, 37,  1,  1,  1,  1,  1, 45,  0, 46,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\11\2\1\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\13\2\0"+
    "\6\2\1\14\5\2\1\0\1\3\7\2\1\15\1\2"+
    "\1\16\1\17\1\0\2\2\1\20\5\2\1\0\2\2"+
    "\1\0\1\2\1\0\2\2\1\21\1\2\1\0\1\2"+
    "\1\22\2\23\1\2\1\24\2\2\1\0\1\25\1\26"+
    "\2\2\1\27\1\30\1\31";

  private static int [] zzUnpackAction() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\u0120\0\u0150"+
    "\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0\0\60"+
    "\0\u02d0\0\60\0\60\0\60\0\60\0\60\0\60\0\220"+
    "\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0\0\u0420\0\140"+
    "\0\u0450\0\u0480\0\u04b0\0\u04e0\0\u0510\0\u0540\0\u0300\0\u0570"+
    "\0\u05a0\0\u05d0\0\u0600\0\u0630\0\u0660\0\u0690\0\140\0\u06c0"+
    "\0\140\0\140\0\u06f0\0\u0720\0\u0750\0\140\0\u0780\0\u07b0"+
    "\0\u07e0\0\u0810\0\u0840\0\u0870\0\u08a0\0\u08d0\0\u0900\0\u0930"+
    "\0\u0960\0\u0990\0\u09c0\0\140\0\u09f0\0\u0a20\0\u0a50\0\140"+
    "\0\60\0\140\0\u0a80\0\140\0\u0ab0\0\u0ae0\0\u0b10\0\140"+
    "\0\140\0\u0b40\0\u0b70\0\60\0\140\0\140";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\2\1\3\2\5\1\6\1\7"+
    "\6\3\1\10\5\3\1\11\1\12\1\3\1\13\2\3"+
    "\1\14\1\15\1\16\3\3\1\17\3\3\1\20\1\6"+
    "\1\2\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\61\0\1\3\1\30\2\0\3\3\1\0\35\3\15\0"+
    "\2\3\61\0\2\5\40\0\1\31\17\0\1\6\36\0"+
    "\1\6\11\0\1\3\1\30\2\0\3\3\1\0\1\3"+
    "\1\32\33\3\13\0\1\3\1\30\2\0\3\3\1\0"+
    "\10\3\1\33\24\3\13\0\1\3\1\30\2\0\3\3"+
    "\1\0\16\3\1\34\10\3\1\35\5\3\13\0\1\3"+
    "\1\30\2\0\3\3\1\0\7\3\1\36\1\3\1\37"+
    "\12\3\1\40\10\3\13\0\1\3\1\30\2\0\3\3"+
    "\1\0\5\3\1\41\27\3\13\0\1\3\1\30\2\0"+
    "\3\3\1\0\14\3\1\42\20\3\13\0\1\3\1\30"+
    "\2\0\3\3\1\0\34\3\1\43\13\0\1\3\1\30"+
    "\2\0\3\3\1\0\2\3\1\44\32\3\13\0\1\3"+
    "\1\30\2\0\3\3\1\0\16\3\1\45\16\3\17\0"+
    "\2\46\4\0\1\46\15\0\1\46\1\0\1\46\32\0"+
    "\2\47\51\0\1\3\1\30\2\0\3\3\1\0\2\3"+
    "\1\50\32\3\13\0\1\3\1\30\2\0\3\3\1\0"+
    "\11\3\1\51\23\3\13\0\1\3\1\30\2\0\3\3"+
    "\1\0\17\3\1\52\15\3\13\0\1\3\1\30\2\0"+
    "\3\3\1\0\11\3\1\53\23\3\13\0\1\3\1\30"+
    "\2\0\3\3\1\0\16\3\1\54\16\3\13\0\1\3"+
    "\1\30\2\0\3\3\1\0\27\3\1\55\5\3\13\0"+
    "\1\3\1\30\2\0\3\3\1\0\21\3\1\56\13\3"+
    "\13\0\1\3\1\30\2\0\3\3\1\0\24\3\1\57"+
    "\10\3\13\0\1\3\1\30\2\0\3\3\1\0\13\3"+
    "\1\60\21\3\13\0\1\3\1\30\2\0\3\3\1\0"+
    "\26\3\1\61\6\3\13\0\1\3\1\30\2\0\3\3"+
    "\1\0\7\3\1\62\25\3\17\0\2\63\4\0\1\63"+
    "\15\0\1\63\1\0\1\63\25\0\1\3\1\30\2\0"+
    "\3\3\1\0\3\3\1\64\31\3\13\0\1\3\1\30"+
    "\2\0\3\3\1\0\12\3\1\65\22\3\13\0\1\3"+
    "\1\30\2\0\3\3\1\0\10\3\1\66\24\3\13\0"+
    "\1\3\1\30\2\0\3\3\1\0\27\3\1\67\5\3"+
    "\13\0\1\3\1\30\2\0\3\3\1\0\30\3\1\70"+
    "\4\3\13\0\1\3\1\30\2\0\3\3\1\0\32\3"+
    "\1\71\2\3\13\0\1\3\1\30\2\0\3\3\1\0"+
    "\22\3\1\72\12\3\13\0\1\3\1\30\2\0\3\3"+
    "\1\0\27\3\1\73\5\3\17\0\2\74\4\0\1\74"+
    "\15\0\1\74\1\0\1\74\25\0\1\3\1\30\2\0"+
    "\3\3\1\0\4\3\1\75\30\3\13\0\1\3\1\30"+
    "\2\0\3\3\1\0\13\3\1\76\21\3\12\0\1\77"+
    "\1\100\1\101\2\77\3\100\1\77\35\100\1\77\1\0"+
    "\10\77\1\0\1\3\1\30\2\0\3\3\1\0\16\3"+
    "\1\102\16\3\13\0\1\3\1\30\2\0\3\3\1\0"+
    "\14\3\1\103\20\3\13\0\1\3\1\30\2\0\3\3"+
    "\1\0\5\3\1\104\27\3\13\0\1\3\1\30\2\0"+
    "\3\3\1\0\30\3\1\105\4\3\17\0\2\106\4\0"+
    "\1\106\15\0\1\106\1\0\1\106\25\0\1\3\1\30"+
    "\2\0\3\3\1\0\5\3\1\107\27\3\13\0\1\3"+
    "\1\30\2\0\3\3\1\0\14\3\1\110\20\3\33\0"+
    "\1\111\37\0\1\3\1\30\2\0\3\3\1\0\10\3"+
    "\1\112\24\3\15\0\1\113\1\3\14\0\1\111\37\0"+
    "\1\3\1\30\2\0\3\3\1\0\10\3\1\114\24\3"+
    "\13\0\1\3\1\30\2\0\3\3\1\0\7\3\1\115"+
    "\25\3\13\0\1\3\1\30\2\0\3\3\1\0\16\3"+
    "\1\116\16\3\17\0\2\117\4\0\1\117\15\0\1\117"+
    "\1\0\1\117\25\0\1\3\1\30\2\0\3\3\1\0"+
    "\6\3\1\120\26\3\13\0\1\3\1\30\2\0\3\3"+
    "\1\0\10\3\1\121\24\3\13\0\1\3\1\30\2\0"+
    "\3\3\1\0\14\3\1\122\20\3\13\0\1\3\1\30"+
    "\2\0\3\3\1\0\10\3\1\123\24\3\17\0\2\124"+
    "\4\0\1\124\15\0\1\124\1\0\1\124\25\0\1\3"+
    "\1\30\2\0\3\3\1\0\33\3\1\125\1\3\13\0"+
    "\1\3\1\30\2\0\3\3\1\0\7\3\1\126\25\3"+
    "\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2976];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\15\1\1\11\1\1\6\11\2\0\14\1"+
    "\1\0\14\1\1\0\10\1\1\0\2\1\1\0\1\1"+
    "\1\0\4\1\1\0\2\1\1\11\5\1\1\0\4\1"+
    "\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    //coidgo de usuario en sintaxis java
    public ArrayList<ErrorG> listaErrores = new  ArrayList<>();
    



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexicoTmp(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AnalizadorLexicoTmp(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { System.out.println("id: "+yytext()); return new Symbol(SimbolosTmp.IDENTIFICADOR , yycolumn, yyline, yytext());
          }
        case 26: break;
        case 7: 
          { System.out.println("CHORCHETE ABRE"); return new Symbol(SimbolosTmp.CORCHETE_A , yycolumn, yyline, yytext());
          }
        case 27: break;
        case 11: 
          { System.out.println("COMA"); return new Symbol(SimbolosTmp.COMA , yycolumn, yyline, yytext());
          }
        case 28: break;
        case 12: 
          { System.out.println("id"); return new Symbol(SimbolosTmp.ID , yycolumn, yyline, yytext());
          }
        case 29: break;
        case 9: 
          { System.out.println("LLAVES ABRE"); return new Symbol(SimbolosTmp.LLAVES_A , yycolumn, yyline, yytext());
          }
        case 30: break;
        case 1: 
          { System.out.println("error Lexico: "+"Columna: "+yycolumn+1+" linea: "+ yyline+1 + "Token: "+yytext());
                                    ErrorG e = new ErrorG(yyline+1, yycolumn+1,yytext(),"Lexico","Error Lexico token: " + yytext()+"   Linea: " + (yyline+1) + " ,    Columna: " + (yycolumn+1));
                                    listaErrores.add(e);
          }
        case 31: break;
        case 19: 
          { System.out.println("TAMANO"); return new Symbol(SimbolosTmp.TAMANIO , yycolumn, yyline, yytext());
          }
        case 32: break;
        case 23: 
          { System.out.println("CODIGO_HEX: "+yytext()); return new Symbol(SimbolosTmp.CODIGO_HEX , yycolumn, yyline, yytext());
          }
        case 33: break;
        case 18: 
          { System.out.println("NOMBRE"); return new Symbol(SimbolosTmp.NOMBRE , yycolumn, yyline, yytext());
          }
        case 34: break;
        case 22: 
          { System.out.println("TAMAIO"); return new Symbol(SimbolosTmp.TAMANIO , yycolumn, yyline, yytext());
          }
        case 35: break;
        case 17: 
          { System.out.println("FONDO"); return new Symbol(SimbolosTmp.FONDO , yycolumn, yyline, yytext());
          }
        case 36: break;
        case 13: 
          { System.out.println("Red"); return new Symbol(SimbolosTmp.RED , yycolumn, yyline, yytext());
          }
        case 37: break;
        case 14: 
          { System.out.println("HEX"); return new Symbol(SimbolosTmp.HEX, yycolumn, yyline, yytext());
          }
        case 38: break;
        case 3: 
          { System.out.println("NUMERO: "+yytext()); return new Symbol(SimbolosTmp.NUMERO , yycolumn, yyline, yytext());
          }
        case 39: break;
        case 10: 
          { System.out.println("LLAVES CIEERRE"); return new Symbol(SimbolosTmp.LLAVES_C , yycolumn, yyline, yytext());
          }
        case 40: break;
        case 16: 
          { System.out.println("TIPO"); return new Symbol(SimbolosTmp.TIPO , yycolumn, yyline, yytext());
          }
        case 41: break;
        case 20: 
          { System.out.println("inicio"); return new Symbol(SimbolosTmp.INICIO_RSRVD , yycolumn, yyline, yytext());
          }
        case 42: break;
        case 15: 
          { System.out.println("fin"); return new Symbol(SimbolosTmp.FIN , yycolumn, yyline, yytext());
          }
        case 43: break;
        case 21: 
          { System.out.println("TIEMPOS"); return new Symbol(SimbolosTmp.TIEMPOS , yycolumn, yyline, yytext());
          }
        case 44: break;
        case 24: 
          { System.out.println("imagenes"); return new Symbol(SimbolosTmp.IMAGENES , yycolumn, yyline, yytext());
          }
        case 45: break;
        case 25: 
          { System.out.println("duracion"); return new Symbol(SimbolosTmp.DURACION , yycolumn, yyline, yytext());
          }
        case 46: break;
        case 6: 
          { System.out.println("dos puntos"); return new Symbol(SimbolosTmp.DOS_PUNTOS , yycolumn, yyline, yytext());
          }
        case 47: break;
        case 4: 
          { /*Ignore*/
          }
        case 48: break;
        case 8: 
          { System.out.println("CORCHE CIERRE"); return new Symbol(SimbolosTmp.CORCHETE_C , yycolumn, yyline, yytext());
          }
        case 49: break;
        case 5: 
          { System.out.println("comillas"); return new Symbol(SimbolosTmp.COMILLAS , yycolumn, yyline, yytext());
          }
        case 50: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(SimbolosTmp.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
