
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 21 16:56:44 CST 2020
//----------------------------------------------------

package analizadores.inz;

/** CUP generated class containing symbol constants. */
public class SimbolosLnz {
  /* terminals */
  public static final int GREEN = 20;
  public static final int LLAVES_C = 6;
  public static final int CODIGO_HEX = 12;
  public static final int LLAVES_A = 5;
  public static final int PNG = 15;
  public static final int BLUE = 19;
  public static final int RED = 18;
  public static final int COMILLAS = 4;
  public static final int HEX = 17;
  public static final int DOS_PUNTOS = 2;
  public static final int TIPO = 14;
  public static final int LIENZOS = 7;
  public static final int COMA = 3;
  public static final int CUADRO = 21;
  public static final int NOMBRE = 13;
  public static final int EOF = 0;
  public static final int FONDO = 11;
  public static final int GIF = 16;
  public static final int error = 1;
  public static final int NUMERO = 10;
  public static final int DIMENSION_Y = 23;
  public static final int DIMENSION_X = 22;
  public static final int IDENTIFICADOR = 9;
  public static final int TAMANIO = 8;
}

